StartupEvents.registry("item", e => {
    //注册双钢锭
    e.create("dimensionalrelics:double_steel")
        .maxStackSize(32)
        .translationKey("item.dimensionalrelics.double_steel")
        .tag("forge:ingots")
        .rarity("rare")
    // 粗铸铁
    e.create("dimensionalrelics:raw_cast_iron_ingot")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.raw_cast_iron_ingot")
        .tag("forge:ingots/raw_steel")
        .rarity("common")
    // 锤炼中的粗铸铁锭
    e.create("dimensionalrelics:hammering_raw_cast_iron_ingot")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.hammering_raw_cast_iron_ingot")
        .tag("forge:ingots/hammering_raw_steel")
        .rarity("common")
    // 太空合金
    e.create("dimensionalrelics:space_alloy_ingot")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.space_alloy_ingot")
        .tag("forge:ingots")
        .tag("forge:ingots/space_alloy")
        .rarity("epic")
    e.create("dimensionalrelics:space_alloy_nugget")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.space_alloy_nugget")
        .tag("forge:nuggets")
        .tag("forge:nuggets/space_alloy")
        .rarity("rare")
    e.create("dimensionalrelics:space_alloy_sheet")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.space_alloy_sheet")
        .tag("forge:plates")
        .tag("forge:plates/space_alloy")
        .rarity("rare")
    e.create("dimensionalrelics:space_alloy_handle")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.space_alloy_handle")
        .tag("forge:rods")
        .tag("forge:rods/space_alloy")
        .rarity("rare")
    // 太空合金构件
    e.create("dimensionalrelics:incompleted_space_alloy_precision_mechanism")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.incompleted_space_alloy_precision_mechanism")
        .rarity("rare")
    e.create("dimensionalrelics:space_alloy_precision_mechanism")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.space_alloy_precision_mechanism")
        .rarity("epic")
    // 辉影合金
    e.create("dimensionalrelics:glow_shadow_alloy")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.glow_shadow_alloy")
        .tag("forge:ingots")
        .tag("forge:ingots/glow_shadow")
        .rarity("epic")
    // 注册铝板
    e.create("tfmg:aluminum_sheet")
        .maxStackSize(64)
        .translationKey("item.tfmg.aluminum_sheet")
        .tag("forge:plates")
        .tag("forge:plates/aluminum")
        .rarity("common")
    // 注册碳板
    e.create("tfmg:coal_sheet")
        .maxStackSize(64)
        .translationKey("item.tfmg.coal_sheet")
        .tag("forge:plates")
        .tag("forge:plates/carbon")
        .rarity("common")
    // 注册锰
    e.create("dimensionalrelics:manganese")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.manganese")
        .tag("forge:ingots")
        .tag("forge:ingots/manganese")
        .rarity("common")
    // 注册粉碎锰矿石
    e.create("dimensionalrelics:crush_raw_manganese")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.crush_raw_manganese")
        .tag("create:crushed_raw_materials")
        .rarity("common")
    // 注册粗锰
    e.create("dimensionalrelics:raw_manganese")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.raw_manganese")
        .tag("forge:raw_materials")
        .tag("forge:raw_materials/manganese")
        .rarity("common")
    // 注册MnO2
    e.create("dimensionalrelics:manganese_dioxide")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.manganese_dioxide")
        .rarity("rare")
    // 注册未完成干电池
    e.create("dimensionalrelics:incompleted_disposable_batteries")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.incompleted_disposable_batteries")
        .rarity("common")
    // 注册干电池
    e.create("dimensionalrelics:disposable_batteries")
        .maxDamage(128000)
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.disposable_batteries")
        .rarity("common")
        .attachCapability(
            CapabilityBuilder.ENERGY.customItemStack()
                .canExtract(() => true)
                .getEnergyStored(be => { return (128000 - be.damageValue) })
                .extractEnergy((item, amount, sim) => {
                    if (item.damageValue < 128000 && !sim) {
                        item.damageValue += Math.min(160, amount)
                    }
                    return Math.min(160, amount)
                })
        )
    // 注册钴
    e.create("dimensionalrelics:cobalt")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.cobalt")
        .tag("forge:ingots")
        .tag("forge:ingots/cobalt")
        .rarity("rare")
    // 注册粉碎钴矿石
    e.create("dimensionalrelics:crush_raw_cobalt")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.crush_raw_cobalt")
        .tag("create:crushed_raw_materials")
        .rarity("common")
    // 注册粗钴
    e.create("dimensionalrelics:raw_cobalt")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.raw_cobalt")
        .tag("forge:raw_materials")
        .tag("forge:raw_materials/cobalt")
        .rarity("common")
    // 注册锂
    e.create("dimensionalrelics:lithium")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.lithium")
        .tag("forge:ingots")
        .tag("forge:ingots/lithium")
        .rarity("rare")
    // 注册粉碎锂矿石
    e.create("dimensionalrelics:crush_raw_lithium")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.crush_raw_lithium")
        .tag("create:crushed_raw_materials")
        .rarity("common")
    // 注册粗锂
    e.create("dimensionalrelics:raw_lithium")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.raw_lithium")
        .tag("forge:raw_materials")
        .tag("forge:raw_materials/lithium")
        .rarity("common")
    // 注册未完成锂电池
    e.create("dimensionalrelics:incompleted_lithium_battery")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.incompleted_lithium_battery")
        .rarity("common")
    // 注册锂电池
    e.create("dimensionalrelics:lithium_battery")
        .maxDamage(1600000)
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.lithium_battery")
        .rarity("rare")
        .attachCapability(
            CapabilityBuilder.ENERGY.customItemStack()
                .canExtract(() => true)
                .getMaxEnergyStored(item => 1600000)
                .receiveEnergy((item, amount, sim) => {
                    const receiveEnergy = Math.min(4000, amount, item.damageValue)
                    if (item.damageValue > 0 && !sim) {
                        item.damageValue -= receiveEnergy
                    }
                    return receiveEnergy
                })
                .canReceive(() => true)
                .getEnergyStored(be => 1600000 - be.damageValue)
                .extractEnergy((item, amount, sim) => {
                    const extractEnergy = Math.min(4000, amount, item.damageValue)
                    if (item.damageValue <= 1600000 && !sim) {
                        item.damageValue += extractEnergy
                    }
                    return extractEnergy
                })
        )
    // 注册碳粉
    e.create("dimensionalrelics:carbon_dust")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.carbon_dust")
        .tag("forge:dusts")
        .tag("forge:dusts/carbon")
        .rarity("rare")
    // 注册碳棒
    e.create("dimensionalrelics:carbon_rod")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.carbon_rod")
        .tag("forge:rods")
        .tag("forge:rods/carbon")
        .rarity("rare")
    // 注册碳酸钠
    e.create("dimensionalrelics:sodium_carbonate")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.sodium_carbonate")
        .rarity("rare")
    // 注册碳酸氢钠
    e.create("dimensionalrelics:sodium_bicarbonate")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.sodium_bicarbonate")
        .rarity("rare")
    // 注册碳酸锂
    e.create("dimensionalrelics:lithium_carbonate")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.lithium_carbonate")
        .rarity("rare")
    // 注册氧化钴
    e.create("dimensionalrelics:cobaltous_oxide")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.cobaltous_oxide")
        .rarity("rare")
    // 钴酸锂
    e.create("dimensionalrelics:lithium_oxidocobalt")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.lithium_oxidocobalt")
        .rarity("rare")
    // 注册海带粉
    e.create("dimensionalrelics:kelp_dust")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.kelp_dust")
        .rarity("common")
    // 注册硅晶片
    e.create("dimensionalrelics:silicon_plate")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.silicon_plate")
        .rarity("common")
    // 注册硅晶圆
    e.create("dimensionalrelics:wafer")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.wafer")
        .rarity("common")
    // 注册掺杂晶元
    e.create("dimensionalrelics:doping_wafer")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.doping_wafer")
        .rarity("rare")
    // 注册化工线相关物品
    e.create("dimensionalrelics:sodium")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.sodium")
        .tag("forge:ingots")
        .rarity("common")
    e.create("dimensionalrelics:urea")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.urea")
        .rarity("common")
    e.create("dimensionalrelics:sodium_hydroxide")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.sodium_hydroxide")
        .rarity("common")
    e.create("dimensionalrelics:polyvinyl_chloride")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.polyvinyl_chloride")
        .tag("forge:ingots/plastic")
        .rarity("common")
    e.create("dimensionalrelics:polystyrene")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.polystyrene")
        .tag("forge:ingots/plastic")
        .rarity("common")
    e.create("dimensionalrelics:polypropylene")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.polypropylene")
        .tag("forge:ingots/plastic")
        .rarity("common")
    e.create("dimensionalrelics:super_polymer")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.super_polymer")
        .tag("forge:ingots/plastic")
        .rarity("common")
    e.create("dimensionalrelics:aviation_fibers")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.aviation_fibers")
        .tag("forge:string")
        .rarity("common")
    e.create("dimensionalrelics:aviation_fibers_sheet")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.aviation_fibers_sheet")
        .tag("forge:plates")
        .rarity("common")
    e.create("dimensionalrelics:sodium_hypochlorite")
        .maxStackSize(64)
        .translationKey("item.dimensionalrelics.sodium_hypochlorite")
        .tag("forge:dusts")
        .rarity("common")

})
